name: Build & Deploy Singularity Containers
on: 
  release:
    types: [published]

  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

jobs:
  build-test-deploy-singularity:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        recipe: ["matlab", "octave"]

    name: Build ${{ matrix.recipe }}
    steps:
    # Install Singularity
    - name: Install Singularity
      run: |
        sudo apt-get update && sudo apt-get install -y singularity-container

    # Pull the Docker image with Singularity and convert it to a SIF file
    - name: Build Singularity image from Docker
      run: |
        singularity pull docker://ghcr.io/spm/spm-docker:docker-${{matrix.recipe}}
        mv spm-docker_docker-${{matrix.recipe}}.sif spm.sif

    - name: Test Container
      run: |
        singularity run spm.sif --version

#       - name: Login and Deploy Container
#         if: |
#           (github.event_name != 'pull_request') &&
#           (github.repository_owner == 'spm')
#         run: |
#           tag=$(basename $(dirname ${{ matrix.recipe }}))
#           if [ "$tag" == "" ]; then
#             tag=latest
#           fi
#           echo "Tag is $tag."
#           echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
#           singularity push spm12.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}

#     # Push Singularity OCI Image to GHCR (optional)
#     - name: Push Singularity OCI Image
#       run: |
#         # Import the SIF as an OCI image and push it to GHCR
#         singularity oci push ghcr.io/spm/spm-docker:docker-${{matrix.recipe}} container.sif
